-- AlterTable
ALTER TABLE "DataRowFinalized" ALTER COLUMN "hookPart2" DROP NOT NULL,
ALTER COLUMN "body1Part2" DROP NOT NULL,
ALTER COLUMN "body2Part2" DROP NOT NULL,
ALTER COLUMN "ctaPart2" DROP NOT NULL;
